### ISSUE TITLE
Give object parameters to component

### ISSUE THREAD

**Issue by mammadyahyayev** [alinacaf10/rendering#1]
https://github.com/alinacaf10/rendering/blob/57a3430585f112da3e6c0efe5433847ad0dbb073/src/App.js#L11-L17

In this part, give console.log to make sure data fetched successfully
```js
componentDidMount = () => { 
   fetchClients().then((client) => { 
    console.log(client); // check here
     this.setState({ 
       client 
     }); 
   }); 
 }; 
```

**Comment by mammadyahyayev** [comment]
If data is available, then pass client to ClientCard component as described in below
```js
<>
  <ClientCard name={client.name}  phone={client.phone} card={client.card} />
</>
```

**Comment by alinacaf10** [comment]
@MamedYahyayev 
https://codesandbox.io/s/clientcardfetch-template-for-lesson-4-7-forked-2th2ot?file=/src/App.js

**Comment by mammadyahyayev** [comment]
> If data is available, then pass client to ClientCard component as described in below
> 
> ```js
> <>
>   <ClientCard name={client.name}  phone={client.phone} card={client.card} />
> </>
> ```

Above code should be like that
```js
<ClientCard
    name={this.state.client.name}
    card={this.state.client.card}
    phone={this.state.client.phone}
/>
```

**Comment by mammadyahyayev** [comment]
Here's the full code: https://codesandbox.io/embed/clientcardfetch-template-for-lesson-4-7-forked-1spmp5?fontsize=14&hidenavigation=1&theme=dark
